[package]
name = "inspector"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A Tauri App"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "inspector_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
# Tauri 의존성
tauri.workspace = true
tauri-plugin-opener.workspace = true

# 워크스페이스 공통 의존성
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

# 서버 라이브러리 의존성 추가
chrome-remote-devtools-server = { path = "../../../crates/server" }

